/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITornadoVault } from "./ITornadoVault";
export type { MockGovernanceForStaking } from "./MockGovernanceForStaking";
