/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dummySol from "./Dummy.sol";
export type { dummySol };
import type * as mockGovernanceForStakingSol from "./MockGovernanceForStaking.sol";
export type { mockGovernanceForStakingSol };
import type * as proposalStateChangeGovernanceSol from "./ProposalStateChangeGovernance.sol";
export type { proposalStateChangeGovernanceSol };
import type * as proposalUpgradeSol from "./ProposalUpgrade.sol";
export type { proposalUpgradeSol };
export type { MockGovernance } from "./MockGovernance";
export type { Proposal } from "./Proposal";
